emusim/cockpit/abm/views/user_views.py
from flask import Blueprint, redirect, render_template, flash
from flask import request, url_for
from flask_user import current_user, login_required, roles_required

from emusim import db
from emusim.cockpit.abm.db.user_models import UserProfileForm, ModelParameters
from emusim.cockpit.abm.forms.abm_forms_d import ParameterForm
from emusim.cockpit.abm.views.abm_d import moneymodel_model

user_blueprint = Blueprint('main', __name__, template_folder='templates')


# The Home page is accessible to anyone
@user_blueprint.route('/main')
def home_page():
    return render_template('main/home_page.html')


# The User page is accessible to authenticated users (users that have logged in)
@user_blueprint.route('/models')
@login_required  # Limits access to authenticated users
def models_page():
    models = ModelParameters.query.filter(ModelParameters.user_id == current_user.id).all()
    return render_template('main/models_page.html', models=models)

@user_blueprint.route('/modeldelete/<modelID>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def delete_model(modelID):
    modelparams = ModelParameters.query.filter(ModelParameters.id == modelID).first()
    if modelparams.user_id == current_user.id:
        db.session.delete(modelparams)
        db.session.commit()
        flash('Your model has been deleted.')
        return redirect(url_for('main.models_page'))
    else:
        flash('Sorry, you have no access to this model')
        return redirect(url_for('abm_in_flask.moneymodel'))


@user_blueprint.route('/modeledit/<modelID>', methods=['GET', 'POST'])
@user_blueprint.route('/modeledit', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def edit_model(modelID=None):
    parameter_form = ParameterForm(request.form)
    if modelID:
        print(modelID)
        modelparams = ModelParameters.query.filter(ModelParameters.id == modelID).first()
        if request.method == 'GET':
            if modelparams.user_id == current_user.id:
                parameter_form = ParameterForm(obj=modelparams)
                return render_template('main/models_edit_page.html', parameter_form=parameter_form)
            else:
                flash('Sorry, you have no access to this model')
                return redirect(url_for('abm_in_flask.moneymodel'))
        if request.method == 'POST':
            parameter_form.populate_obj(modelparams)
            modelparams.id = modelID
            db.session.commit()
            flash('Your model has been updated.')
            return redirect(url_for('main.models_page'))
    # change existing model with the new params
    else:
        if request.method == 'GET':
            return render_template('main/models_edit_page.html', parameter_form=parameter_form)
        # Process valid POST
        if request.method == 'POST' and parameter_form.validate():
            # Copy form fields to user_profile fields

            modelparams = ModelParameters(name=parameter_form.name.data, user_id=current_user.id,
                                          initial_wealth=parameter_form.initial_wealth.data,
                                          wealth_transfer=parameter_form.wealth_transfer.data,
                                          num_agents=parameter_form.num_agents.data,
                                          iterations=parameter_form.iterations.data)
            db.session.add(modelparams)
            db.session.commit()
            # Redirect to models list
            return redirect(url_for('main.models_page'))


@user_blueprint.route('/models/<modelID>')
@login_required  # Limits access to authenticated users
def models_run(modelID):
    model = ModelParameters.query.filter(ModelParameters.id == modelID,
                                         ModelParameters.user_id == current_user.id).first()
    if (not model):
        flash('Model doesn\'t exist or is not accessible')
        return models_page()
    parameter_form = ParameterForm(obj=model)
    return moneymodel_model(model, parameter_form)


# The Admin page is accessible to users with the 'admin' role
@user_blueprint.route('/admin')
@roles_required('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('main/platformusers.html')


@user_blueprint.route('/main/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('abm_in_flask.moneymodel'))

    # Process GET or invalid POST
    return render_template('flask_user/edit_user_profile.html',
                           form=form)

emusim/cockpit/abm/templates/main/home_page.html
{% extends "main/main_base.html" %}  {# main/main_base.html extends layout.html #}

{% block content %}
    <h2>{%trans%}Home page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

emusim/cockpit/abm/templates/main/main_base.html
{% extends "flask_user/_common_base.html" %}

emusim/cockpit/abm/templates/main/models_base.html
{% extends "lorecosim_base.html" %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-8 col-centered">
            {% block content %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

emusim/cockpit/abm/templates/main/models_edit_page.html
{% extends "main/models_base.html" %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<h1>{%trans%}Edit model{%endtrans%}</h1>
<div class="row">
    <div class="col-lg-8 col-md-12">
        <form action="" method="post">
            {{ parameter_form.csrf_token }}
            <div class="card  d-inline-flex mb-2">
                <h5 class="card-header success-color-dark white-text text-center py-4">
                    <strong>Parameter configuration</strong>
                </h5>
                <div class="card-body px-lg-5 pt-0">
                    <table class="outertable">
                        <tr>
                            <td class="tabledata">
                                <table>
                                    <tr>
                                        <td>Provide a model name:</td>
                                        <td>{{ parameter_form.name }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="divider">
                                            <hr/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Model parameters</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="divider">
                                            <hr/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>{{ parameter_form.initial_wealth.label }}</td>
                                        <td>{{ parameter_form.initial_wealth }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{ parameter_form.wealth_transfer.label }}</td>
                                        <td>{{ parameter_form.wealth_transfer }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="divider">
                                            <hr/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>Simulation parameters</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="divider">
                                            <hr/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>{{ parameter_form.num_agents.label }}</td>
                                        <td>{{ parameter_form.num_agents }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{ parameter_form.iterations.label }}</td>
                                        <td>{{ parameter_form.iterations }}</td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </table>
                    <hr>
                    <div class="input submit">
                        <input class=" btn success-color-dark text-white btn-sm button float-right" type="submit"
                               value="Confirm">
                    </div>
                </div>
            </div>
            {% if parameter_form.id.data %}
                <div class="card d-inline-flex mb-2">
                    <div class="card-body">
                        <strong>Delete this model?</strong>
                        <p>Be careful, this deletion is permanent.</p>
                        <a href="{{url_for('main.delete_model', modelID = parameter_form.id.data)}}"
                           class="btn success-color-dark text-white btn-sm button float-right">
                            <i class="fas fa-folder-minus"></i>
                        </a>
                    </div>
                </div>
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

emusim/cockpit/abm/templates/main/models_page.html
{% extends "main/models_base.html" %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_checkbox_field, render_submit_field %}
<h1>{%trans%}Your models{%endtrans%}</h1>
{% if models %}
<table class="table table-sm table-striped">
    <thead>
    <tr>
        <th scope="col">Model name</th>
        <th scope="col">Initial wealth</th>
        <th scope="col">Wealth transfer</th>
        <th scope="col">Agent count</th>
        <th scope="col">Iterations</th>
        <th scope="col">Actions</th>
    </tr>
  </thead>
    <tbody>

    {% for model in models %}
    <tr>
        <td>{{ model.name }}</td>
        <td>{{ model.initial_wealth }}</td>
        <td>{{ model.wealth_transfer }}</td>
        <td>{{ model.num_agents }}</td>
        <td>{{ model.iterations }}</td>
        <td><a href="{{ url_for('main.models_run', modelID=model.id) }}"
                           class="btn success-color-dark text-white btn-sm"><i class="fas fa-running"></i></a>
        <a href="{{ url_for('main.edit_model', modelID=model.id) }}"
                           class="btn success-color-dark text-white btn-sm"><i class="fas fa-edit"></i></a></td>


    </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<h6>{%trans%}You have no saved models yet.{%endtrans%}</h6>
{% endif %}
{% endblock %}