emusim/cockpit/supply/forms/home_forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SelectField, FloatField, IntegerField

from emusim.cockpit.supply.constants import *


class LicenseForm(FlaskForm):
    license_accept = BooleanField('I accept the terms and conditions')

emusim/cockpit/supply/views/home.py
from flask import Blueprint, redirect, request, url_for, render_template
from emusim.cockpit.supply.forms.home_forms import LicenseForm

home = Blueprint('home', __name__,
                 template_folder='../templates',
                 static_folder='../static')


@home.route('/cockpit')
def cockpit():
    return render_template('base.html')


@home.route('/dry', methods=['GET', 'POST'])
def accept_tc():
    license_form = LicenseForm(request.form)

    if license_form.validate_on_submit() and license_form.license_accept.data == True:
        return redirect(url_for("home.cockpit"))

    return render_template('home.html',
                           license_form=license_form)

emusim/cockpit/supply/views/home_d.py
from flask import Blueprint, redirect, request, url_for, render_template
from emusim.cockpit.supply.forms.home_forms import LicenseForm

home_d = Blueprint('home_d', __name__,
                 template_folder='../templates',
                 static_folder='../static')


@home_d.route('/')
def approuter():
    return render_template('approuter.html')

@home_d.route('/cockpit_d')
def cockpit():
    return render_template('base_d.html')


@home_d.route('/design', methods=['GET', 'POST'])
def accept_tc():
    license_form = LicenseForm(request.form)

    if license_form.validate_on_submit() and license_form.license_accept.data == True:
        return redirect(url_for("home_d.cockpit"))

    return render_template('home_d.html',
                           license_form=license_form)


@home_d.route('/home')
def nav():
    return render_template('home_d.html')


@home_d.route('/loreco')
def loreco():
    return redirect('https://www.loreco.be')


@home_d.route('/lorecosimhome')
def lorecosimhome():
    return render_template('lorecosimhome.html')


@home_d.route('/lorecotool')
def lorecotool():
    return render_template('lorecotool.html')

emusim/cockpit/supply/views/sumsy_supply_d.py
from flask import Blueprint, render_template, request
from emusim.cockpit.supply.forms.sumsy_forms_d import ParameterForm, DataSelectionForm

from emusim.cockpit.supply.constants import *
from emusim.cockpit.utilities.utilities import create_chart
from emusim.cockpit.supply.sumsy_simulation import SumSy_MS_Simulation

sumsy_supply_d = Blueprint('sumsy_supply_d', __name__,
                         template_folder='../templates',
                         static_folder='../static')


@sumsy_supply_d.route('/sumsy_supply_simulation_d', methods=['GET', 'POST'])
def sumsy_supply_simulation_d():
    parameter_form = ParameterForm(request.form)
    data_selection_form = DataSelectionForm(request.form)
    render_graphs = False
    crashed = False
    cycles_executed = 0
    equilibrium_balance = 0
    graph_data = []

    if parameter_form.validate_on_submit():
        simulation = SumSy_MS_Simulation()
        simulation.initial_population = parameter_form.population.data
        simulation.population_growth = parameter_form.population_growth.data / 100
        simulation.start_at_saturation =parameter_form.start_at_saturation.data
        simulation.initial_money_mass = parameter_form.money_mass.data
        simulation.initial_inflation_rate = parameter_form.inflation.data / 100
        simulation.initial_income = parameter_form.income.data
        simulation.num_dem_tiers = parameter_form.num_dem_tiers.data

        simulation.initial_dem_tiers[0] = parameter_form.dem_tier_1.data
        simulation.dem_rates[0] = parameter_form.dem_rate_1.data / 100
        simulation.initial_dem_tiers[1] = parameter_form.dem_tier_2.data
        simulation.dem_rates[1] = parameter_form.dem_rate_2.data / 100
        simulation.initial_dem_tiers[2] = parameter_form.dem_tier_3.data
        simulation.dem_rates[2] = parameter_form.dem_rate_3.data / 100
        simulation.initial_dem_tiers[3] = parameter_form.dem_tier_4.data
        simulation.dem_rates[3] = parameter_form.dem_rate_4.data / 100
        simulation.initial_dem_tiers[4] = parameter_form.dem_tier_5.data
        simulation.dem_rates[4] = parameter_form.dem_rate_5.data / 100

        simulation.common_good_spending = parameter_form.common_good_spending.data
        simulation.initial_common_good_budget = parameter_form.common_good_budget.data

        iterations = parameter_form.num_iterations.data

        simulation.run_simulation(iterations)
        crashed = simulation.crash
        cycles_executed = simulation.cycles_executed
        equilibrium_balance = simulation.equilibrium_balance
        graph_data.clear()

        deflate = data_selection_form.deflate.data

        if data_selection_form.population.data:
            population_charts = []
            population_chart = create_chart('Population')
            population_chart.add('Population', simulation.population)

            population_charts.append(population_chart.render_data_uri())
            graph_data.append(population_charts)

        if data_selection_form.money_mass.data:
            money_charts = []
            money_chart = create_chart('Money mass')
            money_chart.add('Money mass', simulation.get_data(simulation.money_mass, 1, cycles_executed, deflate))

            money_charts.append(money_chart.render_data_uri())
            graph_data.append(money_charts)

        if data_selection_form.per_capita_money_mass.data:
            per_capita_money_charts = []
            per_capita_money_chart = create_chart('Money mass per capita')
            per_capita_money_chart.add('Money mass per capita',
                                       simulation.get_data(simulation.per_capita_money_mass, 1, cycles_executed, deflate))

            per_capita_money_charts.append(per_capita_money_chart.render_data_uri())
            graph_data.append(per_capita_money_charts)

        if data_selection_form.demurrage_tiers.data:
            tier_charts = []

            tiers_chart = create_chart('Demurrage tiers')
            tiers_chart.add('Tier 1', simulation.get_data(simulation.get_tier(0), 1, cycles_executed, deflate))
            tiers_chart.add('Tier 2', simulation.get_data(simulation.get_tier(1), 1, cycles_executed, deflate))
            tiers_chart.add('Tier 3', simulation.get_data(simulation.get_tier(2), 1, cycles_executed, deflate))
            tiers_chart.add('Tier 4', simulation.get_data(simulation.get_tier(3), 1, cycles_executed, deflate))
            tiers_chart.add('Tier 5', simulation.get_data(simulation.get_tier(4), 1, cycles_executed, deflate))

            tier_charts.append(tiers_chart.render_data_uri())
            graph_data.append(tier_charts)

        if data_selection_form.demurrage.data:
            demurrage_charts = []

            demurrage_chart = create_chart('Demurrage')
            demurrage_chart.add('Demurrage', simulation.get_data(simulation.demurrage, 1, cycles_executed, deflate))
            demurrage_charts.append(demurrage_chart.render_data_uri())

            graph_data.append(demurrage_charts)

        if data_selection_form.per_capita_demurrage.data:
            per_capita_demurrage_charts = []
            per_capita_demurrage_chart = create_chart('Demurrage per capita')
            per_capita_demurrage_chart.add('Demurrage per capita',
                                           simulation.get_data(simulation.per_capita_demurrage, 1, cycles_executed, deflate))

            per_capita_demurrage_charts.append(per_capita_demurrage_chart.render_data_uri())
            graph_data.append(per_capita_demurrage_charts)

        if data_selection_form.money_cycle.data:
            new_money_charts = []
            new_money_chart = create_chart('Money creation and destruction')
            new_money_chart.add('Money creation',
                                simulation.get_data(simulation.money_cycling, 1, cycles_executed, deflate))

            new_money_charts.append(new_money_chart.render_data_uri())
            graph_data.append(new_money_charts)

        if data_selection_form.per_capita_money_cycle.data:
            per_capita_new_money_charts = []
            per_capita_new_money_chart = create_chart('Money creation and destruction per capita')
            per_capita_new_money_chart.add('Money creation',
                                           simulation.get_data(simulation.per_capita_money_cycling, 1, cycles_executed, deflate))

            per_capita_new_money_charts.append(per_capita_new_money_chart.render_data_uri())
            graph_data.append(per_capita_new_money_charts)

        if data_selection_form.common_good.data:
            common_good_charts = []
            common_good_chart = create_chart('Common good spending')
            common_good_chart.add('Spending', simulation.get_data(simulation.common_good_money, 1, cycles_executed, deflate))
            common_good_charts.append(common_good_chart.render_data_uri())
            graph_data.append(common_good_charts)

        if data_selection_form.percentages.data:
            percentage_charts = []
            percentage_chart = create_chart('Percentages of money mass')
            percentage_chart.add('Income', simulation.get_percentages(simulation.income_percentage, 1, cycles_executed))
            percentage_chart.add('Demurrage',
                                 simulation.get_percentages(simulation.demurrage_percentage, 1, cycles_executed))

            if parameter_form.common_good_spending.data != NONE:
                percentage_chart.add('Common good spending',
                                     simulation.get_percentages(simulation.common_good_percentage, 1, cycles_executed))

            percentage_chart.add('New money',
                                 simulation.get_percentages(simulation.money_cycle_percentage, 1, cycles_executed))

            percentage_charts.append(percentage_chart.render_data_uri())
            graph_data.append(percentage_charts)

        render_graphs = True

    return render_template('sumsy_simulation_d.html',
                           parameter_form=parameter_form,
                           data_selection_form=data_selection_form,
                           crashed=crashed,
                           cycles_executed=cycles_executed,
                           equilibrium_balance=equilibrium_balance,
                           render_graphs=render_graphs,
                           graph_data=graph_data)

emusim/cockpit/supply/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome to the Happonomy cockpit</title>
</head>
<body>
<p>The Happonomy cockpit provides tools for scientific research.</p>
<p>In order to continue, please accept the <a href="https://www.happonomy.org/en/disclaimer/" target="_blank">terms and
    conditions</a>.</p>
<form action="" method="post">
    {{ license_form.csrf_token }}
    <p>{{ license_form.license_accept.label }} {{ license_form.license_accept }}</p>
    <div class="input submit">
        <input class="button" type="submit" value="Continue">
    </div>
</form>
</body>
</html>

emusim/cockpit/supply/templates/home_d.html
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta content="no-cache, no-store, must-revalidate"/>
    <meta content="0"/>

    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!-- Font Awesome -->
    <link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
          rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js" type="text/javascript"></script>
    <!-- Bootstrap tooltips -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"
            type="text/javascript"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"
            type="text/javascript"></script>
    <!-- MDB core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"
            type="text/javascript"></script>

    <title>Economy and Sustainability Simulations</title>
</head>
<body>
<header>

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="#">
                <img alt="happonomy logo"
                     height="30"
                     src="../static/happonomy.svg">
            </a>
            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link waves-effect" href="#">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                    <!-- Dropdown -->


                </ul>

                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons">
                    <li class="nav-item">
                        <a href="https://www.facebook.com/happonomy/" class="nav-link waves-effect" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://twitter.com/happonomy" class="nav-link waves-effect" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://github.com/HapponomyOrg"
                           class="nav-link border border-light rounded waves-effect"
                           target="_blank">
                            <i class="fab fa-github mr-2"></i>Happonomy GitHub
                        </a>
                    </li>
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->

</header>
<!--Main Navigation-->
<main class="mt-5 pt-5">
    <div class="container">

        <!--Section: Jumbotron-->
        <section class="card aqua-gradient wow fadeIn" id="intro">

            <!-- Content -->
            <div class="card-body text-white text-center py-5 px-5 my-5">

                <h1 class="mb-4">
                    <strong>Happonomy Terms and Conditions</strong>
                </h1>
                <h2 class="mb-4">
                    Please accept to continue...
                </h2>
                <p>The Happonomy cockpit provides tools for scientific research.</p>
                <p>In order to continue, please accept the <a href="https://www.happonomy.org/en/disclaimer/" target="_blank">terms and
                    conditions</a>.</p>
                <form action="" method="post">
                    {{ license_form.csrf_token }}
                    <p>{{ license_form.license_accept.label }} {{ license_form.license_accept }}</p>
                    <div class="input submit">
                        <input class="button" type="submit" value="Continue">
                    </div>
                </form>

            </div>
            <!-- Content -->
        </section>
        <!--Section: Jumbotron-->

        <hr class="my-5">



    </div>
</main>
<!--Main layout-->

<!--Footer-->
<footer class="page-footer text-center font-small info-color white-text mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">


        <a class="btn btn-outline-white" href="https://www.happonomy.org" target="_blank"
           role="button">Happonomy

        </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">



    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2019 Copyright:
        <a href="https://www.happonomy.org" target="_blank"> Happonomy </a>
    </div>
    <!--/.Copyright-->

</footer>
<!--/.Footer-->

<div class="container text-center wow fadeInUp">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message[1] }}</li>
        {% endfor %}
    </ul>
    <hr>
    {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}

</div>


<hr>


</body>
</html>

emusim/cockpit/supply/templates/sumsy_simulation_d.html
{% extends "happonomysim.html" %}

{% block content %}
<div class="row d-flex justify-content-center">
    <h2>SuMSy Supply Simulation</h2>
</div>
{% if not render_graphs %}
<form action="" method="post">
    {{ parameter_form.csrf_token }}
    <div class="card  d-inline-flex  mb-2">
        <h5 class="card-header info-color white-text text-center py-4">
            <strong>Simulation parameters</strong>
        </h5>
        <div class="card-body px-lg-5 pt-0">

            <table class="outertable">
                <tr>
                    <td class="tabledata">
                        <table>
                            <tr>
                                <td>{{ parameter_form.num_iterations.label }}</td>
                                <td>{{ parameter_form.num_iterations }}</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.population.label }}</td>
                                <td>{{ parameter_form.population }}</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.population_growth.label }}</td>
                                <td>{{ parameter_form.population_growth }}</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.start_at_saturation.label }}</td>
                                <td>{{ parameter_form.start_at_saturation }}</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.money_mass.label }}</td>
                                <td>{{ parameter_form.money_mass }}</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.income.label }}</td>
                                <td>{{ parameter_form.income }}</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.inflation.label }}</td>
                                <td>{{ parameter_form.inflation }}</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.num_dem_tiers.label }}</td>
                                <td>{{ parameter_form.num_dem_tiers }}</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.dem_tier_1.label }}</td>
                                <td>{{ parameter_form.dem_tier_1 }}</td>
                                <td>{{ parameter_form.dem_rate_1 }}</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.dem_tier_2.label }}</td>
                                <td>{{ parameter_form.dem_tier_2 }}</td>
                                <td>{{ parameter_form.dem_rate_2 }}</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.dem_tier_3.label }}</td>
                                <td>{{ parameter_form.dem_tier_3 }}</td>
                                <td>{{ parameter_form.dem_rate_3 }}</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.dem_tier_4.label }}</td>
                                <td>{{ parameter_form.dem_tier_4 }}</td>
                                <td>{{ parameter_form.dem_rate_4 }}</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.dem_tier_5.label }}</td>
                                <td>{{ parameter_form.dem_tier_5 }}</td>
                                <td>{{ parameter_form.dem_rate_5 }}</td>
                                <td>%</td>
                            </tr>
                            <tr>
                                <td colspan="3" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.common_good_spending.label }}</td>
                                <td>{{ parameter_form.common_good_spending }}</td>
                            </tr>
                            <tr>
                                <td>{{ parameter_form.common_good_budget.label }}</td>
                                <td>{{ parameter_form.common_good_budget }}</td>
                            </tr>
                        </table>
                    </td>

                </tr>
            </table>
            <hr>


        </div>
    </div>
    <div class="card  d-inline-flex  mb-2">
        <h5 class="card-header info-color white-text text-center py-4">
            <strong>Output specification</strong>
        </h5>
        <div class="card-body px-lg-5 pt-0">

            <table class="outertable">
                <tr>
                    <td class="tabledata">

                        <table>

                            <tr>
                                <td>{{ data_selection_form.population.label }}</td>
                                <td>{{ data_selection_form.population }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.deflate.label }}</td>
                                <td>{{ data_selection_form.deflate }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.money_mass.label }}</td>
                                <td>{{ data_selection_form.money_mass }}</td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.per_capita_money_mass.label }}</td>
                                <td>{{ data_selection_form.per_capita_money_mass }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.demurrage_tiers.label }}</td>
                                <td>{{ data_selection_form.demurrage_tiers }}</td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.demurrage.label }}</td>
                                <td>{{ data_selection_form.demurrage }}</td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.per_capita_demurrage.label }}</td>
                                <td>{{ data_selection_form.per_capita_demurrage }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.money_cycle.label }}</td>
                                <td>{{ data_selection_form.money_cycle }}</td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.per_capita_money_cycle.label }}</td>
                                <td>{{ data_selection_form.per_capita_money_cycle }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.common_good.label }}</td>
                                <td>{{ data_selection_form.common_good }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" class="divider">
                                    <hr/>
                                </td>
                            </tr>
                            <tr>
                                <td>{{ data_selection_form.percentages.label }}</td>
                                <td>{{ data_selection_form.percentages }}</td>
                            </tr>
                        </table>
                    </td>

                </tr>
            </table>
            <hr>
            <div class="input submit">
        <input class=" btn btn-primary btn-sm button" type="submit" value="Run">
    </div>

        </div>
    </div>



</form>
{% endif %}
{% if render_graphs %}
<div class="row"><div class="col">Equilibruim balance for this simulation: {{ equilibrium_balance }} <a class="btn btn-primary btn-sm float-right" type="button"
       href="{{ url_for('sumsy_supply_d.sumsy_supply_simulation_d') }}">New simulation</a></div></div>
{% if crashed %}
<div class="row"><div class="col">Crashed: ran for {{ cycles_executed }} cycles</div></div>
{% endif %}
<div class="container">
    <div class="row">


        {% for graphs in graph_data %}
        {% for graph in graphs %}
        <div class="col-md-6">
            <img src={{graph|safe}} class="img-fluid p-2" style="width:100%">
        </div>

        {% endfor %}
        {% endfor %}


    </div>

</div>
{% endif %}
{% endblock %}