emusim/cockpit/abm/views/abm_d.py
from flask import Blueprint, render_template, request
from flask_login import current_user

from emusim.cockpit.abm.forms.abm_forms_d import ParameterForm
from emusim.cockpit.abm.mesa.MoneyModel import *
import pygal
import numpy as np


abm_in_flask = Blueprint('abm_in_flask', __name__,
                         template_folder='../templates',
                         static_folder='../static')

graph_data = []

def model_run(model_params):
    graph_data.clear()
    parameter_form = ParameterForm(request.form)
    parameter_form.initial_wealth.data = model_params.initial_wealth
    parameter_form.wealth_transfer.data = model_params.wealth_transfer
    parameter_form.num_agents.data = model_params.agents_count
    parameter_form.iterations.data = model_params.iterations_count
    gridsize = int(round(parameter_form.num_agents.data / 5))
    model = MoneyModel(parameter_form.num_agents.data, gridsize, gridsize, parameter_form.initial_wealth.data,
                       parameter_form.wealth_transfer.data)
    for i in range(parameter_form.iterations.data):
        model.step()
    gini = model.datacollector.get_model_vars_dataframe()
    arr = np.transpose(gini.values)[0]

    # create gini chart
    gini_charts = []
    chart_gini = pygal.Line(show_dots=True, show_legend=False,
                            range=(0, 1), show_x_labels=True)
    chart_gini.title = 'Gini coefficient'
    chart_gini.add('Gini', arr)
    chart_gini.render()
    gini_charts.append(chart_gini.render_data_uri())
    graph_data.append(gini_charts)
    render_graphs = True
    return render_template('abm_simulation_d.html',
                       parameter_form=parameter_form,
                       graph_data=graph_data,
                       render_graphs=render_graphs)


def moneymodel_model(model, parameter_form):
    render_graphs = True
    graph_data = moneymodel_run(model.num_agents, model.initial_wealth, model.wealth_transfer,
                                model.iterations)
    return render_template('abm_simulation_d.html',
                            parameter_form=parameter_form,
                            graph_data=graph_data,
                            render_graphs=render_graphs)


def moneymodel_run(num_agents, initial_wealth, wealth_transfer, iterations):
    # run model
    graph_data.clear()
    gridsize = int(round(num_agents / 5))
    model = MoneyModel(num_agents, gridsize, gridsize, initial_wealth,
                       wealth_transfer)
    for i in range(iterations):
        model.step()
    gini = model.datacollector.get_model_vars_dataframe()
    arr = np.transpose(gini.values)[0]

    # create gini chart
    gini_charts = []
    chart_gini = pygal.Line(show_dots=True, show_legend=False,
                            range=(0, 1), show_x_labels=True)
    chart_gini.title = 'Gini coefficient'
    chart_gini.add('Gini', arr)
    chart_gini.render()
    gini_charts.append(chart_gini.render_data_uri())
    graph_data.append(gini_charts)
    return graph_data


@abm_in_flask.route('/moneymodel', methods=['GET', 'POST'])
def moneymodel(parameter_form=None):
    if (not parameter_form):
        parameter_form = ParameterForm(request.form)
    render_graphs = False
    graph_data = None
    if parameter_form.validate():
        graph_data = moneymodel_run(parameter_form.num_agents.data, parameter_form.initial_wealth.data,
                                    parameter_form.wealth_transfer.data, parameter_form.iterations.data)
        render_graphs = True

    return render_template('abm_simulation_d.html',
                           parameter_form=parameter_form,
                           graph_data=graph_data,
                           render_graphs=render_graphs)

emusim/cockpit/abm/views/user_views.py
from flask import Blueprint, redirect, render_template, flash
from flask import request, url_for
from flask_user import current_user, login_required, roles_required

from emusim import db
from emusim.cockpit.abm.db.user_models import UserProfileForm, ModelParameters
from emusim.cockpit.abm.forms.abm_forms_d import ParameterForm
from emusim.cockpit.abm.views.abm_d import moneymodel_model

user_blueprint = Blueprint('main', __name__, template_folder='templates')


# The Home page is accessible to anyone
@user_blueprint.route('/main')
def home_page():
    return render_template('main/home_page.html')


# The User page is accessible to authenticated users (users that have logged in)
@user_blueprint.route('/models')
@login_required  # Limits access to authenticated users
def models_page():
    models = ModelParameters.query.filter(ModelParameters.user_id == current_user.id).all()
    return render_template('main/models_page.html', models=models)

@user_blueprint.route('/modeldelete/<modelID>', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def delete_model(modelID):
    modelparams = ModelParameters.query.filter(ModelParameters.id == modelID).first()
    if modelparams.user_id == current_user.id:
        db.session.delete(modelparams)
        db.session.commit()
        flash('Your model has been deleted.')
        return redirect(url_for('main.models_page'))
    else:
        flash('Sorry, you have no access to this model')
        return redirect(url_for('abm_in_flask.moneymodel'))


@user_blueprint.route('/modeledit/<modelID>', methods=['GET', 'POST'])
@user_blueprint.route('/modeledit', methods=['GET', 'POST'])
@login_required  # Limits access to authenticated users
def edit_model(modelID=None):
    parameter_form = ParameterForm(request.form)
    if modelID:
        print(modelID)
        modelparams = ModelParameters.query.filter(ModelParameters.id == modelID).first()
        if request.method == 'GET':
            if modelparams.user_id == current_user.id:
                parameter_form = ParameterForm(obj=modelparams)
                return render_template('main/models_edit_page.html', parameter_form=parameter_form)
            else:
                flash('Sorry, you have no access to this model')
                return redirect(url_for('abm_in_flask.moneymodel'))
        if request.method == 'POST':
            parameter_form.populate_obj(modelparams)
            modelparams.id = modelID
            db.session.commit()
            flash('Your model has been updated.')
            return redirect(url_for('main.models_page'))
    # change existing model with the new params
    else:
        if request.method == 'GET':
            return render_template('main/models_edit_page.html', parameter_form=parameter_form)
        # Process valid POST
        if request.method == 'POST' and parameter_form.validate():
            # Copy form fields to user_profile fields

            modelparams = ModelParameters(name=parameter_form.name.data, user_id=current_user.id,
                                          initial_wealth=parameter_form.initial_wealth.data,
                                          wealth_transfer=parameter_form.wealth_transfer.data,
                                          num_agents=parameter_form.num_agents.data,
                                          iterations=parameter_form.iterations.data)
            db.session.add(modelparams)
            db.session.commit()
            # Redirect to models list
            return redirect(url_for('main.models_page'))


@user_blueprint.route('/models/<modelID>')
@login_required  # Limits access to authenticated users
def models_run(modelID):
    model = ModelParameters.query.filter(ModelParameters.id == modelID,
                                         ModelParameters.user_id == current_user.id).first()
    if (not model):
        flash('Model doesn\'t exist or is not accessible')
        return models_page()
    parameter_form = ParameterForm(obj=model)
    return moneymodel_model(model, parameter_form)


# The Admin page is accessible to users with the 'admin' role
@user_blueprint.route('/admin')
@roles_required('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('main/platformusers.html')


@user_blueprint.route('/main/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('abm_in_flask.moneymodel'))

    # Process GET or invalid POST
    return render_template('flask_user/edit_user_profile.html',
                           form=form)

emusim/cockpit/supply/views/home.py
from flask import Blueprint, redirect, request, url_for, render_template
from emusim.cockpit.supply.forms.home_forms import LicenseForm

home = Blueprint('home', __name__,
                 template_folder='../templates',
                 static_folder='../static')


@home.route('/cockpit')
def cockpit():
    return render_template('base.html')


@home.route('/dry', methods=['GET', 'POST'])
def accept_tc():
    license_form = LicenseForm(request.form)

    if license_form.validate_on_submit() and license_form.license_accept.data == True:
        return redirect(url_for("home.cockpit"))

    return render_template('home.html',
                           license_form=license_form)

emusim/cockpit/supply/views/home_d.py
from flask import Blueprint, redirect, request, url_for, render_template
from emusim.cockpit.supply.forms.home_forms import LicenseForm

home_d = Blueprint('home_d', __name__,
                 template_folder='../templates',
                 static_folder='../static')


@home_d.route('/')
def approuter():
    return render_template('approuter.html')

@home_d.route('/cockpit_d')
def cockpit():
    return render_template('base_d.html')


@home_d.route('/design', methods=['GET', 'POST'])
def accept_tc():
    license_form = LicenseForm(request.form)

    if license_form.validate_on_submit() and license_form.license_accept.data == True:
        return redirect(url_for("home_d.cockpit"))

    return render_template('home_d.html',
                           license_form=license_form)


@home_d.route('/home')
def nav():
    return render_template('home_d.html')


@home_d.route('/loreco')
def loreco():
    return redirect('https://www.loreco.be')


@home_d.route('/lorecosimhome')
def lorecosimhome():
    return render_template('lorecosimhome.html')


@home_d.route('/lorecotool')
def lorecotool():
    return render_template('lorecotool.html')

emusim/templates/approuter.html
<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml" xmlns:display="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!-- Font Awesome -->
    <link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
          rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js" type="text/javascript"></script>
    <!-- Bootstrap tooltips -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"
            type="text/javascript"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"
            type="text/javascript"></script>
    <!-- MDB core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"
            type="text/javascript"></script>

    <link href="favicon.ico" rel="icon" type="image/x-icon">

    <title>LoREco project</title>
</head>
<body>
<header>

</header>
<main class="mt-2 pt-4">
    <div class="container">

        <h3 class="my-5 h3 text-center">Available Simulation Environments</h3>

        <!--Grid row-->
        <div class="row d-flex justify-content-center">

            <!--Grid column-->
            <div class="col-md-8 text-center">

                <p class="mb-5"></p>

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="container ">
            <div class="row text-center wow fadeIn d-flex justify-content-center">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                    <!--Card-->
                    <div class="card">

                        <!-- Card header -->
                        <div class="card-header">
                            <h4>
                                <strong>Happonomy Simulations</strong>
                            </h4>
                        </div>

                        <!--Card content-->
                        <div class="card-body">

                            <h3 class="card-title pricing-card-title mb-4">
                                <small class="text-muted">Simulation tools on sustainability in the economy</small>
                            </h3>

                            <ol class="list-unstyled mb-4">
                                <li>Structural modelling
                                    <i class="fas fa-check green-text ml-1"></i>
                                </li>
                                <hr>
                                <li>3 tools
                                    <i class="fas fa-check green-text ml-1"></i>
                                </li>


                            </ol>

                            <a type="button" class="btn btn-lg waves-effect btn-dark-green"
                               href="{{ url_for('home.accept_tc') }}">Dry
                            </a>
                            <a type="button" class="btn btn-lg waves-effect btn-dark-green"
                               href="{{ url_for('home_d.accept_tc') }}">Design
                            </a>
                        </div>

                    </div>
                    <!--/.Card-->

                </div>
                <!--Grid column-->


                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <!--Card-->
                    <div class="card">

                        <!-- Card header -->
                        <div class="card-header">
                            <h4>
                                <strong>LoREco Simulation</strong>
                            </h4>
                        </div>

                        <!--Card content-->
                        <div class="card-body">

                            <h3 class="card-title pricing-card-title mb-4">
                                <small class="text-muted">Sustainability and basic income simulation tool</small>
                            </h3>

                            <ol class="list-unstyled mb-4">
                                <li>Agent-based modelling
                                    <i class="fas fa-check green-text ml-1"></i>
                                </li>
                                <hr>
                                <li>1 tool
                                    <i class="fas fa-check green-text ml-1"></i>
                                </li>


                            </ol>

                            <a type="button" class="btn btn-lg btn-block waves-effect btn-dark-green"
                               href="{{ url_for('home_d.lorecosimhome') }}">Get Started
                            </a>
                        </div>

                    </div>
                    <!--/.Card-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->
        </div>
    </div>
</main>

<footer class="page-footer text-center font-small mt-4 wow fadeIn">

</footer>
</body>

emusim/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="no-cache, no-store, must-revalidate" />
    <meta content="0" />
    <link rel="stylesheet" type="text/css" href="../static/style.css">
    <title>Economy and Sustainability Simulations</title>
</head>
    <body>
        <div>
            <a href="{{ url_for('euro_supply.euro_supply_simulation') }}">Euro Supply Simulation</a>
            <a href="{{ url_for('sumsy_supply.sumsy_supply_simulation') }}">SuMSy Supply Simulation</a>
            <a href="{{ url_for('overshoot.overshoot_simulation') }}">Earth Overshoot Simulation</a>
        </div>
        <hr>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <ul>
                {% for message in messages %}
                    <li>{{ message[1] }}</li>
                {% endfor %}</ul>
                <hr>
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </body>
</html>

emusim/templates/lorecosim.html
<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml" xmlns:display="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!-- Font Awesome -->
    <link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
          rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js" type="text/javascript"></script>
    <!-- Bootstrap tooltips -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"
            type="text/javascript"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"
            type="text/javascript"></script>
    <!-- MDB core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"
            type="text/javascript"></script>

    <link href="favicon.ico" rel="icon" type="image/x-icon">
    <link href="../static/lorecosim.css" rel="stylesheet">
    <title>LoREco project</title>
</head>

<body>
<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark success-color-dark">
        <a class="navbar-brand" href="#"><strong>LoREco</strong></a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('home_d.lorecosimhome') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('abm_in_flask.moneymodel')}}">Simulation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('home_d.lorecotool')}}">On the simtool</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home_d.loreco') }}" target="_blank"><i
                            class="fas fa-angle-double-right"></i>More on LoREco
                    </a>
                </li>

            </ul>
        </div>
        <a class="navbar-brand ml-auto" href="">
            <img alt="loreco logo"
                 height="40"
                 src="../static/logo_Loreco.png">
        </a>
    </nav>


</header>
<main class="mt-5 pt-5">
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message[1] }}</li>
            {% endfor %}
        </ul>
        <hr>
        {% endif %}
        {% endwith %}

        {% block content %}{% endblock %}
    </div>
</main>
<footer class="page-footer text-center font-small success-color-dark white-text mt-4 wow fadeIn">

    <!--Copyright-->
    <div class="footer-copyright py-3">
        © 2020 Copyright:
        <a href="https://www.loreco.be" target="_blank"> LoREco </a>
    </div>
    <!--/.Copyright-->

</footer>
</body>

emusim/templates/lorecosim_base.html
<html lang="en" xmlns:th="http://www.w3.org/1999/xhtml" xmlns:display="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <!-- Font Awesome -->
    <link href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
          rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
    <!-- JQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js" type="text/javascript"></script>
    <!-- Bootstrap tooltips -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"
            type="text/javascript"></script>
    <!-- Bootstrap core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"
            type="text/javascript"></script>
    <!-- MDB core JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"
            type="text/javascript"></script>

    <link href="{{ url_for('static', filename='logo_Loreco_csmall.png') }}" rel="icon" type="image/png">
    <link href="../static/lorecosim.css" rel="stylesheet">
    <style>
        hr { border-color: #cccccc; margin: 0; }
        .no-margins { margin: 0px; }
        .with-margins { margin: 10px; }
        .col-centered { float: none; margin: 0 auto; }
    </style>
    <title>LoREco project</title>
</head>

<body>
<header>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark success-color-dark">
        <a class="navbar-brand" href="#">
            <img alt="loreco logo"
                 height="40"
                 src="../static/logo_Loreco.png">
            <strong>LoREco</strong>
        </a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('home_d.lorecosimhome') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('abm_in_flask.moneymodel')}}">Simulation</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('home_d.lorecotool')}}">On the simtool</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('home_d.loreco') }}" target="_blank"><i
                            class="fas fa-angle-double-right"></i>More on LoREco
                    </a>
                </li>

            </ul>
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i></a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-default"
                         aria-labelledby="navbarDropdownMenuLink">
                        {{ current_user.first_name or current_user.username or
                        current_user.email }}
                        <hr>
                        {% if current_user.has_roles('admin') %}
                        <a class="dropdown-item nav-link waves-effect text-dark"
                           href="{{ url_for('admin.platformusers_page') }}">Platform users</a>
                        <a class="dropdown-item nav-link waves-effect text-dark"
                           href="{{ url_for('admin.platformmodels_page') }}">Platform models</a>
                        <hr>
                        {% endif %}
                        <a class="dropdown-item nav-link waves-effect text-dark"
                           href="{{ url_for('main.models_page') }}">My models</a>
                        <a class="dropdown-item nav-link waves-effect text-dark"
                           href="{{ url_for('main.user_profile_page') }}">My profile</a>
                        <a class="dropdown-item nav-link waves-effect text-dark"
                           href="{{ url_for('user.logout') }}">Sign out</a>

                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">Sign in</a>
                </li>
                {% endif %}


            </ul>
        </div>

    </nav>


</header>
<main class="mt-5 pt-5">
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message[1] }}</li>
            {% endfor %}
        </ul>
        <hr>
        {% endif %}
        {% endwith %}
        {% block main %}
            {% block content %}{% endblock %}
        {% endblock %}
    </div>
</main>
<footer class="page-footer text-center font-small success-color-dark white-text mt-4 wow fadeIn">

    <!--Copyright-->
    <div class="footer-copyright py-3">
        <a href="https://www.loreco.be" target="_blank"> LoREco </a>
    </div>
    <!--/.Copyright-->

</footer>
</body>

emusim/templates/lorecotool.html
{% extends "lorecosim_base.html" %}
{% block content %}
    <div class="container">
        <p class="mb-5">Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo qui laboriosam nihil
            reiciendis fugit eius nostrum
            ipsum odio, voluptate debitis laborum perspiciatis voluptatibus? Culpa expedita rem totam eos fugit
            atque!</p>
        <p class="mb-5">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
            Vestibulum
            tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas
            semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien
            ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean
            fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec
            non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque
            egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan
            porttitor, facilisis luctus, metus</p>
    </div>
{% endblock %}